#ifndef VM_STATUS_H
#define VM_STATUS_H

typedef enum vm_status {
    VM_OK,
    VM_ERROR_HAS_PROGRAM,
    VM_ERROR_NOT_INITIALIZED,
    VM_ERROR_SEGMENTATION_FAULT,
    VM_ERROR_STACK_OVERFLOW,
    VM_ERROR_INVALID_PROGRAM,
    VM_INFO_CPU_IDLE,
    VM_INFO_CPU_HALT,
    VM_WARN_CPU_NO_INSTRUCTIONS,
    VM_ERROR_OUT_OF_BOUNDS
} vm_status_t;

#endif